<nav>
    <div class="nav-wrapper">
        <a href="index.php" class="brand-logo"><?= $this->logo() ?></a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <?php foreach ($this->links() as $link) : ?>
                <?= $link->getHtml() ?>
            <?php endforeach; ?>
        </ul>
        <ul class="side-nav" id="mobile-demo">
            <?php foreach ($this->links() as $link) : ?>
                <?= $link->getHtml() ?>
            <?php endforeach; ?>
        </ul>
    </div>
</nav>
<script>
    $(".button-collapse").sideNav();
</script>
